
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.test.openmeetings.calendarservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T11:51:07.402+08:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "org.apache.openmeetings.webservice.CalendarWebService",
                      portName = "CalendarWebServicePort",
                      targetNamespace = "http://webservice.openmeetings.apache.org/",
                      wsdlLocation = "http://192.168.0.25:5080/openmeetings/services/CalendarService?wsdl",
                      endpointInterface = "com.test.openmeetings.calendarservice.CalendarWebService")

public class CalendarWebServicePortImpl implements CalendarWebService {

    private static final Logger LOG = Logger.getLogger(CalendarWebServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#getByTitle(java.lang.String sid, java.lang.String title)*
     */
    public java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> getByTitle(java.lang.String sid, java.lang.String title) {
        LOG.info("Executing operation getByTitle");
        System.out.println(sid);
        System.out.println(title);
        try {
            java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#next(java.lang.String sid)*
     */
    public com.test.openmeetings.calendarservice.AppointmentDTO next(java.lang.String sid) {
        LOG.info("Executing operation next");
        System.out.println(sid);
        try {
            com.test.openmeetings.calendarservice.AppointmentDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#nextForUser(java.lang.String sid, long userid)*
     */
    public com.test.openmeetings.calendarservice.AppointmentDTO nextForUser(java.lang.String sid, long userid) {
        LOG.info("Executing operation nextForUser");
        System.out.println(sid);
        System.out.println(userid);
        try {
            com.test.openmeetings.calendarservice.AppointmentDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#getByRoom(java.lang.String sid, long roomid)*
     */
    public com.test.openmeetings.calendarservice.AppointmentDTO getByRoom(java.lang.String sid, long roomid) {
        LOG.info("Executing operation getByRoom");
        System.out.println(sid);
        System.out.println(roomid);
        try {
            com.test.openmeetings.calendarservice.AppointmentDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#range(java.lang.String sid, javax.xml.datatype.XMLGregorianCalendar start, javax.xml.datatype.XMLGregorianCalendar end)*
     */
    public java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> range(java.lang.String sid, javax.xml.datatype.XMLGregorianCalendar start, javax.xml.datatype.XMLGregorianCalendar end) {
        LOG.info("Executing operation range");
        System.out.println(sid);
        System.out.println(start);
        System.out.println(end);
        try {
            java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#rangeForUser(java.lang.String sid, long userid, javax.xml.datatype.XMLGregorianCalendar start, javax.xml.datatype.XMLGregorianCalendar end)*
     */
    public java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> rangeForUser(java.lang.String sid, long userid, javax.xml.datatype.XMLGregorianCalendar start, javax.xml.datatype.XMLGregorianCalendar end) {
        LOG.info("Executing operation rangeForUser");
        System.out.println(sid);
        System.out.println(userid);
        System.out.println(start);
        System.out.println(end);
        try {
            java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#save(java.lang.String sid, com.test.openmeetings.calendarservice.AppointmentDTO appointment)*
     */
    public com.test.openmeetings.calendarservice.AppointmentDTO save(java.lang.String sid, com.test.openmeetings.calendarservice.AppointmentDTO appointment) {
        LOG.info("Executing operation save");
        System.out.println(sid);
        System.out.println(appointment);
        try {
            com.test.openmeetings.calendarservice.AppointmentDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.openmeetings.calendarservice.CalendarWebService#delete(java.lang.String sid, java.lang.Long id)*
     */
    public com.test.openmeetings.calendarservice.ServiceResult delete(java.lang.String sid, java.lang.Long id) {
        LOG.info("Executing operation delete");
        System.out.println(sid);
        System.out.println(id);
        try {
            com.test.openmeetings.calendarservice.ServiceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
