
package com.test.openmeetings.calendarservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T11:51:07.418+08:00
 * Generated source version: 3.3.5
 *
 */

public class CalendarWebService_CalendarWebServicePort_Server{

    protected CalendarWebService_CalendarWebServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new CalendarWebServicePortImpl();
        String address = "http://192.168.0.25:5080/openmeetings/services/CalendarService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new CalendarWebService_CalendarWebServicePort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
