
package com.test.openmeetings.calendarservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-02T11:51:07.389+08:00
 * Generated source version: 3.3.5
 *
 */
public final class CalendarWebService_CalendarWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.openmeetings.apache.org/", "org.apache.openmeetings.webservice.CalendarWebService");

    private CalendarWebService_CalendarWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OrgApacheOpenmeetingsWebserviceCalendarWebService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OrgApacheOpenmeetingsWebserviceCalendarWebService ss = new OrgApacheOpenmeetingsWebserviceCalendarWebService(wsdlURL, SERVICE_NAME);
        CalendarWebService port = ss.getCalendarWebServicePort();

        {
        System.out.println("Invoking getByTitle...");
        java.lang.String _getByTitle_sid = "";
        java.lang.String _getByTitle_title = "";
        java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _getByTitle__return = port.getByTitle(_getByTitle_sid, _getByTitle_title);
        System.out.println("getByTitle.result=" + _getByTitle__return);


        }
        {
        System.out.println("Invoking next...");
        java.lang.String _next_sid = "";
        com.test.openmeetings.calendarservice.AppointmentDTO _next__return = port.next(_next_sid);
        System.out.println("next.result=" + _next__return);


        }
        {
        System.out.println("Invoking nextForUser...");
        java.lang.String _nextForUser_sid = "";
        long _nextForUser_userid = 0;
        com.test.openmeetings.calendarservice.AppointmentDTO _nextForUser__return = port.nextForUser(_nextForUser_sid, _nextForUser_userid);
        System.out.println("nextForUser.result=" + _nextForUser__return);


        }
        {
        System.out.println("Invoking getByRoom...");
        java.lang.String _getByRoom_sid = "";
        long _getByRoom_roomid = 0;
        com.test.openmeetings.calendarservice.AppointmentDTO _getByRoom__return = port.getByRoom(_getByRoom_sid, _getByRoom_roomid);
        System.out.println("getByRoom.result=" + _getByRoom__return);


        }
        {
        System.out.println("Invoking range...");
        java.lang.String _range_sid = "";
        javax.xml.datatype.XMLGregorianCalendar _range_start = null;
        javax.xml.datatype.XMLGregorianCalendar _range_end = null;
        java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _range__return = port.range(_range_sid, _range_start, _range_end);
        System.out.println("range.result=" + _range__return);


        }
        {
        System.out.println("Invoking rangeForUser...");
        java.lang.String _rangeForUser_sid = "";
        long _rangeForUser_userid = 0;
        javax.xml.datatype.XMLGregorianCalendar _rangeForUser_start = null;
        javax.xml.datatype.XMLGregorianCalendar _rangeForUser_end = null;
        java.util.List<com.test.openmeetings.calendarservice.AppointmentDTO> _rangeForUser__return = port.rangeForUser(_rangeForUser_sid, _rangeForUser_userid, _rangeForUser_start, _rangeForUser_end);
        System.out.println("rangeForUser.result=" + _rangeForUser__return);


        }
        {
        System.out.println("Invoking save...");
        java.lang.String _save_sid = "";
        com.test.openmeetings.calendarservice.AppointmentDTO _save_appointment = null;
        com.test.openmeetings.calendarservice.AppointmentDTO _save__return = port.save(_save_sid, _save_appointment);
        System.out.println("save.result=" + _save__return);


        }
        {
        System.out.println("Invoking delete...");
        java.lang.String _delete_sid = "";
        java.lang.Long _delete_id = null;
        com.test.openmeetings.calendarservice.ServiceResult _delete__return = port.delete(_delete_sid, _delete_id);
        System.out.println("delete.result=" + _delete__return);


        }

        System.exit(0);
    }

}
