
package com.test.meetings.userwebService;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-23T15:14:08.187+08:00
 * Generated source version: 3.3.5
 *
 */

public class UserWebService_UserService_Server{

    protected UserWebService_UserService_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new UserServiceImpl();
        String address = "http://192.168.0.25:5080/openmeetings/services/UserService";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new UserWebService_UserService_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
