
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.test.meetings.userwebService;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-02-23T15:14:08.171+08:00
 * Generated source version: 3.3.5
 *
 */

@javax.jws.WebService(
                      serviceName = "org.apache.openmeetings.webservice.UserWebService",
                      portName = "UserService",
                      targetNamespace = "http://webservice.openmeetings.apache.org/",
                      wsdlLocation = "http://192.168.0.25:5080/openmeetings/services/UserService?wsdl",
                      endpointInterface = "com.test.meetings.userwebService.UserWebService")

public class UserServiceImpl implements UserWebService {

    private static final Logger LOG = Logger.getLogger(UserServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#add(java.lang.String sid, com.test.meetings.userwebService.UserDTO user, java.lang.Boolean confirm)*
     */
    public com.test.meetings.userwebService.UserDTO add(java.lang.String sid, com.test.meetings.userwebService.UserDTO user, java.lang.Boolean confirm) {
        LOG.info("Executing operation add");
        System.out.println(sid);
        System.out.println(user);
        System.out.println(confirm);
        try {
            com.test.meetings.userwebService.UserDTO _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#get(java.lang.String sid)*
     */
    public java.util.List<com.test.meetings.userwebService.UserDTO> get(java.lang.String sid) {
        LOG.info("Executing operation get");
        System.out.println(sid);
        try {
            java.util.List<com.test.meetings.userwebService.UserDTO> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#getRoomHash(java.lang.String sid, com.test.meetings.userwebService.ExternalUserDTO user, com.test.meetings.userwebService.RoomOptionsDTO options)*
     */
    public com.test.meetings.userwebService.ServiceResult getRoomHash(java.lang.String sid, com.test.meetings.userwebService.ExternalUserDTO user, com.test.meetings.userwebService.RoomOptionsDTO options) {
        LOG.info("Executing operation getRoomHash");
        System.out.println(sid);
        System.out.println(user);
        System.out.println(options);
        try {
            com.test.meetings.userwebService.ServiceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#delete(java.lang.String sid, long id)*
     */
    public com.test.meetings.userwebService.ServiceResult delete(java.lang.String sid, long id) {
        LOG.info("Executing operation delete");
        System.out.println(sid);
        System.out.println(id);
        try {
            com.test.meetings.userwebService.ServiceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#deleteExternal(java.lang.String sid, java.lang.String externaltype, java.lang.String externalid)*
     */
    public com.test.meetings.userwebService.ServiceResult deleteExternal(java.lang.String sid, java.lang.String externaltype, java.lang.String externalid) {
        LOG.info("Executing operation deleteExternal");
        System.out.println(sid);
        System.out.println(externaltype);
        System.out.println(externalid);
        try {
            com.test.meetings.userwebService.ServiceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.test.meetings.userwebService.UserWebService#login(java.lang.String user, java.lang.String pass)*
     */
    public com.test.meetings.userwebService.ServiceResult login(java.lang.String user, java.lang.String pass) {
        LOG.info("Executing operation login");
        System.out.println(user);
        System.out.println(pass);
        try {
            com.test.meetings.userwebService.ServiceResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
